controller_manager:
  ros__parameters:
    update_rate: 100
    use_sim_time: true
    
    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    arm_controller:
      type: joint_trajectory_controller/JointTrajectoryController

arm_controller:
  ros__parameters:
    joints:
      - slider_joint
      - revolute_arm
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
    open_loop_control: true
    allow_partial_joints_goal: false
    constraints:
      stopped_velocity_tolerance: 0.01
      goal_time: 0.0